export const ROUTE_NAME = {
    HOME: 'Homepage',
    SERVICES: 'Services',
    HOW_TO_PRESCRIBE: 'How to prescribe',
    HOW_COMPOUNDING_WORKS: 'How compounding works',
    OUR_FACILITY: 'Our facility',
    OUR_COMMITMENTS: 'Our commitments',
    KNOWLEDGE_CENTER: 'Knowledge center',
    KNOWLEDGE_CENTER_ARTICLE: 'Knowledge center article',
    FAQ: 'FAQ',
    PATIENT_PORTAL_SIGNUP: 'Patient portal signup',
    PATIENT_PORTAL_SIGNIN: 'Patient portal signin',
    TRANSFER_RX: 'Transfer RX',
    NEW_PATIENT: 'New patient',
    BOOK_A_CONSULTATION: 'Book a consultation',
    CONTACT_US: 'Contact us',
    MY_PROFILE: 'My profile',
    WRITE_COMPOUNDED_RX: 'How to write a compounded Rx',
    UNAVAILABLE_MEDICATIONS: 'Unavailable medications',
    PPA: 'Professional partnership / Accreditation',
    BHRT_SERVICE: 'Biological Hormone Replacement Therapy (BHRT)',
    WEIGHT_LOSS_SERVICE: 'Weight Loss Compounding',
    SEXUAL_HEALTH_SERVICE: 'Sexual health for men & women',
    LDN_SERVICE: 'Low-Dose Naltrexone (LDN)',
    HAIR_LOSS_SERVICE: 'Hair loss solutions',
    DERMATO_LOGICAL_SERVICE: 'Dermatological preparations',
    PEDIATRICS_SERVICE: 'Pediatrics',
    VETERINARY_SERVICE: 'Veterinary compounding'
}

export const PATH = {
    HOME: '/',
    SERVICES: '/services',
    HOW_TO_PRESCRIBE: '/how-to-prescribe',
    HOW_COMPOUNDING_WORKS: '/how-compounding-works',
    OUR_FACILITY: '/our-facility',
    OUR_COMMITMENTS: '/our-commitments',
    KNOWLEDGE_CENTER: '/knowledge-center',
    KNOWLEDGE_CENTER_ARTICLE: '/knowledge-center/article/:id',
    FAQ: '/faq',
    PATIENT_PORTAL_SIGNUP: '/patient-portal/signup',
    PATIENT_PORTAL_SIGNIN: '/patient-portal/signin',
    TRANSFER_RX: '/transfer-rx',
    NEW_PATIENT: '/new-patient',
    BOOK_A_CONSULTATION: '/book-a-consultation',
    CONTACT_US: '/contact-us',
    MY_PROFILE: '/my-profile',
    WRITE_COMPOUNDED_RX: '/how-to-write-a-compounded-rx',
    UNAVAILABLE_MEDICATIONS: '/unavailable-medications',
    PPA: '/ppa',
    BHRT_SERVICE: '/services/bhrt',
    WEIGHT_LOSS_SERVICE: '/services/weight-loss-compounding',
    SEXUAL_HEALTH_SERVICE: '/services/sexual-health-for-men-and-women',
    LDN_SERVICE: '/services/ldn',
    HAIR_LOSS_SERVICE: '/services/hair-loss-solutions',
    DERMATO_LOGICAL_SERVICE: '/services/dermatological-preparations',
    PEDIATRICS_SERVICE: '/services/pediatrics',
    VETERINARY_SERVICE: '/services/veterinary-compounding'
}